export const ufStates = [
  { value: 12, label: 'AC - Acre' },
  { value: 27, label: 'AL - Alagoas' },
  { value: 16, label: 'AP - Amapá' },
  { value: 13, label: 'AM - Amazonas' },
  { value: 29, label: 'BA - Bahia' },
  { value: 23, label: 'CE - Ceará' },
  { value: 53, label: 'DF - Distrito Federal' },
  { value: 32, label: 'ES - Espírito Santo' },
  { value: 52, label: 'GO - Goiás' },
  { value: 21, label: 'MA - Maranhão' },
  { value: 51, label: 'MT - Mato Grosso' },
  { value: 50, label: 'MS - Mato Grosso do Sul' },
  { value: 31, label: 'MG - Minas Gerais' },
  { value: 15, label: 'PA - Pará' },
  { value: 25, label: 'PB - Paraíba' },
  { value: 41, label: 'PR - Paraná' },
  { value: 26, label: 'PE - Pernambuco' },
  { value: 22, label: 'PI - Piauí' },
  { value: 33, label: 'RJ - Rio de Janeiro' },
  { value: 24, label: 'RN - Rio Grande do Norte' },
  { value: 43, label: 'RS - Rio Grande do Sul' },
  { value: 11, label: 'RO - Rondônia' },
  { value: 14, label: 'RR - Roraima' },
  { value: 42, label: 'SC - Santa Catarina' },
  { value: 35, label: 'SP - São Paulo' },
  { value: 28, label: 'SE - Sergipe' },
  { value: 17, label: 'TO - Tocantins' }
];